import Vue from 'vue';
import WinAlerts from '@base/js/ui/components/WinAlerts';
import WinButton from '@base/js/ui/components/WinButton';
import WinCaptcha from '@base/js/ui/components/WinCaptcha';
import WinList from '@base/js/ui/components/WinList';
import WinMemo from '@base/js/ui/components/WinMemo';
import WinNewsLoader from '@base/js/ui/components/WinNewsLoader';
import WinPagination from '@base/js/ui/components/WinPagination';
import WinPlayerReactions from '@base/js/ui/components/WinPlayerReactions';
import WinPlayerTime from '@base/js/ui/components/WinPlayerTime';
import WinSongInfo from '@base/js/ui/components/WinSongInfo';
import WinTaskbar from '@base/js/ui/components/WinTaskbar';
import WinWindow from '@base/js/ui/components/WinWindow.vue';

Vue.component('win-alerts', WinAlerts);
Vue.component('win-btn', WinButton);
Vue.component('win-captcha', WinCaptcha);
Vue.component('win-list', WinList);
Vue.component('win-memo', WinMemo);
Vue.component('win-news-loader', WinNewsLoader);
Vue.component('win-pagination', WinPagination);
Vue.component('win-player-reactions', WinPlayerReactions);
Vue.component('win-player-time', WinPlayerTime);
Vue.component('win-song-info', WinSongInfo);
Vue.component('win-taskbar', WinTaskbar);
Vue.component('win-window', WinWindow);
