import Vue from 'vue';
import WindowAbout from '@common/windows/WindowAbout';
import WindowAlert from '@common/windows/WindowAlert';
import WindowCredits from '@common/windows/WindowCredits';
import WindowHistory from '@common/windows/WindowHistory';
import WindowNews from '@common/windows/WindowNews';
import WindowRatings from '@common/windows/WindowRatings';
import WindowSettingsBackground from '@common/windows/WindowSettingsBackground';
import WindowSong from '@common/windows/WindowSong';
import WindowUser from '@common/windows/WindowUser';
import WindowUserEmail from '@common/windows/WindowUserEmail';
import WindowUserFavorites from '@common/windows/WindowUserFavorites';
import WindowUserLogin from '@common/windows/WindowUserLogin';
import WindowUserPassword from '@common/windows/WindowUserPassword';
import WindowUserRegister from '@common/windows/WindowUserRegister';
import WindowUserReset from '@common/windows/WindowUserReset';

Vue.component('window-about', WindowAbout);
Vue.component('window-alert', WindowAlert);
Vue.component('window-credits', WindowCredits);
Vue.component('window-history', WindowHistory);
Vue.component('window-news', WindowNews);
Vue.component('window-ratings', WindowRatings);
Vue.component('window-settings-background', WindowSettingsBackground);
Vue.component('window-song', WindowSong);
Vue.component('window-user', WindowUser);
Vue.component('window-user-email', WindowUserEmail);
Vue.component('window-user-favorites', WindowUserFavorites);
Vue.component('window-user-login', WindowUserLogin);
Vue.component('window-user-password', WindowUserPassword);
Vue.component('window-user-register', WindowUserRegister);
Vue.component('window-user-reset', WindowUserReset);
