project_id: "893416"
base_path: "."
preserve_hierarchy: true

files:
  - source: src/locales/en-US.json
    translation: src/locales/%locale%.json
    dest: "/Nightwave Plaza App/NightwavePlaza.json"
