project_id: "893416"
base_path: "."
preserve_hierarchy: true

files:
  - source: src/locales/en_US.json
    translation: src/locales/%locale_with_underscore%.json
    dest: "/Nightwave Plaza App/NightwavePlaza.json"
