import Vue from 'vue';
import WinAlerts from '@common/components/WinAlerts';
import WinButton from '@common/components/WinButton';
import WinCaptcha from '@common/components/WinCaptcha';
import WinList from '@common/components/WinList';
import WinMemo from '@common/components/WinMemo';
import WinNewsLoader from '@common/components/WinNewsLoader';
import WinPagination from '@common/components/WinPagination';
import WinPlayerReactions from '@common/components/WinPlayerReactions';
import WinPlayerTime from '@common/components/WinPlayerTime';
import WinSongInfo from '@common/components/WinSongInfo';
import WinTaskbar from '@common/components/WinTaskbar';
import WinWindow from '@common/components/WinWindow.vue';

Vue.component('win-alerts', WinAlerts);
Vue.component('win-btn', WinButton);
Vue.component('win-captcha', WinCaptcha);
Vue.component('win-list', WinList);
Vue.component('win-memo', WinMemo);
Vue.component('win-news-loader', WinNewsLoader);
Vue.component('win-pagination', WinPagination);
Vue.component('win-player-reactions', WinPlayerReactions);
Vue.component('win-player-time', WinPlayerTime);
Vue.component('win-song-info', WinSongInfo);
Vue.component('win-taskbar', WinTaskbar);
Vue.component('win-window', WinWindow);
