import Vue from 'vue';
import WindowAbout from '@base/windows/WindowAbout';
import WindowAlert from '@base/windows/WindowAlert';
import WindowCredits from '@base/windows/WindowCredits';
import WindowHistory from '@base/windows/WindowHistory';
import WindowNews from '@base/windows/WindowNews';
import WindowRatings from '@base/windows/WindowRatings';
import WindowSettingsBackground from '@base/windows/WindowSettingsBackground';
import WindowSong from '@base/windows/WindowSong';
import WindowUser from '@base/windows/WindowUser';
import WindowUserEmail from '@base/windows/WindowUserEmail';
import WindowUserFavorites from '@base/windows/WindowUserFavorites';
import WindowUserLogin from '@base/windows/WindowUserLogin';
import WindowUserPassword from '@base/windows/WindowUserPassword';
import WindowUserRegister from '@base/windows/WindowUserRegister';
import WindowUserReset from '@base/windows/WindowUserReset';

Vue.component('window-about', WindowAbout);
Vue.component('window-alert', WindowAlert);
Vue.component('window-credits', WindowCredits);
Vue.component('window-history', WindowHistory);
Vue.component('window-news', WindowNews);
Vue.component('window-ratings', WindowRatings);
Vue.component('window-settings-background', WindowSettingsBackground);
Vue.component('window-song', WindowSong);
Vue.component('window-user', WindowUser);
Vue.component('window-user-email', WindowUserEmail);
Vue.component('window-user-favorites', WindowUserFavorites);
Vue.component('window-user-login', WindowUserLogin);
Vue.component('window-user-password', WindowUserPassword);
Vue.component('window-user-register', WindowUserRegister);
Vue.component('window-user-reset', WindowUserReset);
