export const AndroidBridge = {
  getStatus: () => Promise.resolve(JSON.parse(AndroidInterface.getStatus())),
  requestUiUpdate: () => AndroidInterface.requestUiUpdate(),
  audioPlay: () => AndroidInterface.audioPlay(),
  audioStop: () => AndroidInterface.audioStop(),
  setSleepTimer: (time) => AndroidInterface.setSleepTimer(time),
  getAuthToken: () => Promise.resolve(AndroidInterface.getAuthToken()),
  setAuthToken: (token) => AndroidInterface.setAuthToken(token),
  getAudioQuality: () => Promise.resolve(AndroidInterface.getAudioQuality()),
  setAudioQuality: (lowQuality) => AndroidInterface.setAudioQuality(lowQuality),
  toggleFullscreen: () => AndroidInterface.toggleFullscreen(),
  openDrawer: () => AndroidInterface.openDrawer(),
  getUserAgent: () => Promise.resolve(AndroidInterface.getUserAgent()),
  getAppVersion: () => Promise.resolve(AndroidInterface.getVersion()),
  setBackground: (background) => AndroidInterface.setBackground(background),
  setReaction: (score) => AndroidInterface.setReaction(score),
  getReaction: () => Promise.resolve(JSON.parse(AndroidInterface.getReaction())),
}
