name: Build View Release

on:
  push:
    tags:
      - 'v*'

env:
  VITE_API_URL: https://api.plaza.one
  VITE_TURNSTILE_KEY: ${{ secrets.TURNSTILE_KEY }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: yarn

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Set Version Variable
        run: echo "APP_VERSION=${GITHUB_REF_NAME#v}" >> $GITHUB_ENV

      # --- BUILD APP ---
      - name: Build app target
        run: |
          rm -rf dist
          VITE_APP=app yarn build
          mv dist dist-app

      # --- BUILD MOBILE ---
      - name: Build mobile target
        run: |
          rm -rf dist
          VITE_APP=mobile yarn build
          mv dist dist-mobile

      # --- ZIP APP ---
      #- name: Zip app build
      #  run: |
      #    cd dist-app
      #    zip -r ../build-app-${{ env.APP_VERSION }}.zip .
      #    cd ..

      # --- ZIP MOBILE ---
      - name: Zip mobile build
        run: |
          cd dist-mobile
          zip -r ../build-mobile-${{ env.APP_VERSION }}.zip .
          cd ..

      # --- CREATE RELEASE ---
      #- name: Create GitHub Release
      #  uses: softprops/action-gh-release@v2
      #  with:
      #    tag_name: v${{ github.event.inputs.version }}
      #    name: v${{ github.event.inputs.version }}
      #    draft: false
      #    prerelease: false
      #    files: |
      #      build-app-${{ github.event.inputs.version }}.zip
      #      build-mobile-${{ github.event.inputs.version }}.zip
      #  env:
      #    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # --- UPLOAD RELEASE TO S3 ---
      - name: Install MinIO client
        run: |
          curl https://dl.min.io/client/mc/release/linux-amd64/mc \
          --create-dirs \
          -o $HOME/minio-binaries/mc
          chmod +x $HOME/minio-binaries/mc
          echo "$HOME/minio-binaries" >> $GITHUB_PATH

      - name: Configure MinIO
        run: |
          mc alias set gh-deploy ${{ secrets.MINIO_ENDPOINT }} \
          ${{ secrets.MINIO_ACCESS_KEY }} \
          ${{ secrets.MINIO_SECRET_KEY }}

      - name: Upload to MinIO
        run: |
          mc cp build-mobile-${{ env.APP_VERSION }}.zip \
          gh-deploy/${{ secrets.MINIO_BUCKET }}/${{ env.APP_VERSION }}/build-mobile-${{ env.APP_VERSION }}.zip
        env:
          MINIO_BUCKET: ${{ secrets.MINIO_BUCKET }}
          MINIO_ENDPOINT: ${{ secrets.MINIO_ENDPOINT }}

      - name: Update version manifest
        run: |
          # Get min android version
          MIN_ANDROID=$(jq -r '.min_android_version' version_manifest.json)
          
          # Download manifest file
          mc cp gh-deploy/${{ secrets.MINIO_BUCKET }}/update-manifest.json ./manifest.json || echo '{"versions":[]}' > manifest.json
          
          # Set download url
          DOWNLOAD_URL="${{ secrets.MINIO_ENDPOINT }}/${{ secrets.MINIO_BUCKET }}/${{ env.APP_VERSION }}/build-mobile-${{ env.APP_VERSION }}.zip"
          
          # Calculate hash
          FILE_HASH=$(sha256sum build-mobile-${{ env.APP_VERSION }}.zip | awk '{ print $1 }')
          
          # Update manifest for new version
          jq --arg av "$MIN_ANDROID" \
             --arg vv "${{ env.APP_VERSION }}" \
             --arg url "$DOWNLOAD_URL" \
             --arg hash "$FILE_HASH" \
             '(.versions | map(if .min_android == ($av|tonumber) then .view_version = ($vv|tonumber) | .url = $url | .sha256 = $hash else . end)) as $new_list | 
              if ($new_list | any(.min_android == ($av|tonumber))) then .versions = $new_list else .versions += [{"min_android": ($av|tonumber), "view_version": ($vv|tonumber), "url": $url, "sha256": $hash}] end' \
             manifest.json > new_manifest.json
          
          # Upload new manifest
          mc cp new_manifest.json gh-deploy/${{ secrets.MINIO_BUCKET }}/update-manifest.json
        env:
          MINIO_BUCKET: ${{ secrets.MINIO_BUCKET }}
